### ISSUE TITLE
编译不了

### ISSUE THREAD

**Issue by wenweiming** [zl810881283/Academia-Writing-with-Markdown-Using-Pandoc#1]
您好，很高兴你能分享你的markdown作品。
我直接下载了你的作品，但是我用pandoc运行的`pandoc --filter pandoc-crossref --filter pandoc-citeproc --biblio reference.bib --csl chinese-gb7714-2005-numeric.csl --latex-engine=xelatex  main.md -o main.doc`的时候，出现`pandoc.exe: Could not find data file templates\my.latex`的错误。这怎么解决呢。

Thanks!

**Comment by wenweiming** [comment]
错误是Could not find executable 'pandoc-crossref'.，不好意思。

**Comment by zl810881283** [comment]
看下我博文，需要预先安装好pandoc-crossref @wenweiming 
```
cabal install pandoc #安装 pandoc
cabal install pandoc-crossref #安装 pandoc 交叉引用支持
cabal install pandoc-citeproc #安装 pandoc 参考文献支持
```

**Comment by zl810881283** [comment]
```
cabal install pandoc #安装 pandoc
cabal install pandoc-crossref #安装 pandoc 交叉引用支持
cabal install pandoc-citeproc #安装 pandoc 参考文献支持
```

**Comment by wenweiming** [comment]
好的，谢谢。我是在windows上面选择直接安装软件的方法，没有安装 Haskell 平台。有空试试看。
